[package]
name = "lclass-renamer"
version = "0.1.0"
authors = ["Nora <ncos@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
